version: '3.7'

services:

  vobe:
    image: vobe
    container_name: vobe_node
    build:
      context: .
      target: node
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./vobe/:/vobe
      - .:/home/node/app
    networks:
      - vobe

  nginx:
    container_name: vobe_web
    build:
      context: .
      target: web
    restart: always
    depends_on:
      - vobe
    volumes:
      - ./data/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vobe

  # Mongo installation is now defined in vobe-gql
  #mongo:
  #  image: mongo
  #  container_name: vobe_mongo
  #  restart: always
  #  ports:
  #    - "27017:27017"
  #  volumes:
  #    - mongodata:/data/db
  #  networks:
  #    - vobe

volumes:
  mongodata:

networks:
  vobe:
    external: true
