version: '3.7'

services:

  vobe:
    image: vobe
    container_name: vobe_node
    build:
      context: .
      target: node
    restart: always
    environment:
      LETSENCRYPT_EMAIL: contact.vobe@gmail.com
      LETSENCRYPT_HOST: api.vobe.io
      VIRTUAL_HOST: api.vobe.io
      VIRTUAL_PORT: 80
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./vobe/:/vobe
      - .:/home/node/app

  nginx:
    container_name: vobe_web
    build:
      context: .
      target: web
    restart: always
    environment:
      LETSENCRYPT_EMAIL: contact.vobe@gmail.com
      LETSENCRYPT_HOST: vobe.io, www.vobe.io
      VIRTUAL_HOST: vobe.io, www.vobe.io
      VIRTUAL_PORT: 80
    depends_on:
      - vobe
    volumes:
      - ./data/conf/nginx.conf:/etc/nginx/conf.d/default.conf

  mongo:
    image: mongo
    container_name: vobe_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  proxy:
    image: jwilder/nginx-proxy
    container_name: vobe_proxy
    restart: unless-stopped
    volumes:
      - ./vobe/certs:/etc/nginx/certs
      - ./data/conf:/etc/nginx/conf.d
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/vhosts:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock
    ports:
      - 80:80
      - 443:443
    environment:
      DEFAULT_HOST: vobe.io
      DEFAULT_EMAIL: timoaeckerle@gmx.de
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  ssl_provider:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: vobe_ssl_provider
    restart: unless-stopped
    depends_on:
      - proxy
    volumes:
      - ./vobe/certs:/etc/nginx/certs
      - ./data/conf:/etc/nginx/conf.d
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/vhosts:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongodata:
