version: '3.7'

services:

  vobe:
    image: vobe
    container_name: vobe_node
    build:
      context: .
      target: node
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 8080:${web_port}
    volumes:
      - ./vobe/:/vobe
      - .:/home/node/app
    env_file:
      - .env

  nginx:
    build:
      context: .
      target: web
    restart: always
    ports:
    - 80:80

  mongo:
    image: mongo
    container_name: vobe_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    env_file:
      - .env

volumes:
  mongodata:
